<a href="https://colab.research.google.com/github/Miciomicioso/vino/blob/master/Vino5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np
import csv
data_path="https://raw.githubusercontent.com/Miciomicioso/vino/master/winequality-red.csv "
data_numpy=np.loadtxt(data_path,dtype=np.float32,delimiter=";",skiprows=1)

print(data_numpy.shape)
x=torch.from_numpy(data_numpy)
y=x[:1499,11]
y_test=x[1499:,11]
print(y)
x_input=x[:1499,:11]
x_test=x[1499:,:11]

print(x_input.shape)
print(x_test.shape)
print(y.shape)
print(y_test.shape)

(1599, 12)
tensor([5., 5., 5.,  ..., 5., 6., 6.])
torch.Size([1499, 11])
torch.Size([100, 11])
torch.Size([1499])
torch.Size([100])


In [6]:
w= torch.rand(1,11,requires_grad=True)
b= torch.rand(1)
print(w)
print(b)

tensor([[0.3741, 0.5547, 0.2221, 0.7856, 0.6503, 0.1694, 0.7579, 0.6939, 0.7582,
         0.5287, 0.2206]], requires_grad=True)
tensor([0.1919])


In [7]:
import torch.nn as nn
model=nn.Linear(11,1,True)

#print(model.weight)
#print(model.bias)

In [8]:
n_iter =10
learning_rate=0.01
loss=nn.MSELoss()
for i in range(n_iter):
  pred=model(x_input[i])
  l=loss(y,pred)
  print(l)
  #print(pred)

tensor(131.1539, grad_fn=<MeanBackward0>)
tensor(414.5913, grad_fn=<MeanBackward0>)
tensor(289.9642, grad_fn=<MeanBackward0>)
tensor(329.3618, grad_fn=<MeanBackward0>)
tensor(131.1539, grad_fn=<MeanBackward0>)
tensor(173.5723, grad_fn=<MeanBackward0>)
tensor(348.9013, grad_fn=<MeanBackward0>)
tensor(54.1298, grad_fn=<MeanBackward0>)
tensor(44.6007, grad_fn=<MeanBackward0>)
tensor(958.1973, grad_fn=<MeanBackward0>)


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:432: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1499])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
