<a href="https://colab.research.google.com/github/Miciomicioso/vino/blob/master/Vino5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np
import csv
data_path="https://raw.githubusercontent.com/Miciomicioso/vino/master/winequality-red.csv "
data_numpy=np.loadtxt(data_path,dtype=np.float32,delimiter=";",skiprows=1)

print(data_numpy.shape)
x=torch.from_numpy(data_numpy)
y=x[:1499,11]
y_test=x[1499:,11]
print(y)
x_input=x[:1499,:11]
x_test=x[1499:,:11]

print(x_input.shape)
print(x_test.shape)
print(y.shape)
print(y_test.shape)

(1599, 12)
tensor([5., 5., 5.,  ..., 5., 6., 6.])
torch.Size([1499, 11])
torch.Size([100, 11])
torch.Size([1499])
torch.Size([100])


In [6]:
w= torch.rand(1,11,requires_grad=True)
b= torch.rand(1)
print(w)
print(b)

tensor([[0.3741, 0.5547, 0.2221, 0.7856, 0.6503, 0.1694, 0.7579, 0.6939, 0.7582,
         0.5287, 0.2206]], requires_grad=True)
tensor([0.1919])


In [7]:
import torch.nn as nn
model=nn.Linear(11,1,True)

#print(model.weight)
#print(model.bias)

In [10]:
n_iter =10
learning_rate=0.01
loss=nn.MSELoss()
for i in range(n_iter):
  pred=model(x_input[i])
  l=loss(y[i],pred)
  print(l)
  print(pred)

tensor(116.3552, grad_fn=<MeanBackward0>)
tensor([-5.7868], grad_fn=<AddBackward0>)
tensor(388.4362, grad_fn=<MeanBackward0>)
tensor([-14.7088], grad_fn=<AddBackward0>)
tensor(268.0558, grad_fn=<MeanBackward0>)
tensor([-11.3724], grad_fn=<AddBackward0>)
tensor(342.0135, grad_fn=<MeanBackward0>)
tensor([-12.4936], grad_fn=<AddBackward0>)
tensor(116.3552, grad_fn=<MeanBackward0>)
tensor([-5.7868], grad_fn=<AddBackward0>)
tensor(156.5763, grad_fn=<MeanBackward0>)
tensor([-7.5130], grad_fn=<AddBackward0>)
tensor(324.8901, grad_fn=<MeanBackward0>)
tensor([-13.0247], grad_fn=<AddBackward0>)
tensor(75.2666, grad_fn=<MeanBackward0>)
tensor([-1.6756], grad_fn=<AddBackward0>)
tensor(63.8733, grad_fn=<MeanBackward0>)
tensor([-0.9921], grad_fn=<AddBackward0>)
tensor(918.5524, grad_fn=<MeanBackward0>)
tensor([-25.3076], grad_fn=<AddBackward0>)


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:432: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
