<a href="https://colab.research.google.com/github/Miciomicioso/vino/blob/master/Vino5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import csv
data_path="https://raw.githubusercontent.com/Miciomicioso/vino/master/winequality-red.csv "
data_numpy=np.loadtxt(data_path,dtype=np.float32,delimiter=";",skiprows=1)

print(data_numpy.shape)
x=torch.from_numpy(data_numpy)
y=x[:1499,11]
y_test=x[1499:,11]
print(y)
x_input=x[:1499,:11]
x_test=x[1499:,:11]

print(x_input.shape)
print(x_test.shape)
print(y.shape)
print(y_test.shape)

(1599, 12)
tensor([5., 5., 5.,  ..., 5., 6., 6.])
torch.Size([1499, 11])
torch.Size([100, 11])
torch.Size([1499])
torch.Size([100])


In [2]:
w= torch.rand(1,11,requires_grad=True)
b= torch.rand(1)
print(w)
print(b)

tensor([[0.5695, 0.7554, 0.0251, 0.4298, 0.1200, 0.3796, 0.7740, 0.3142, 0.4522,
         0.0368, 0.3043]], requires_grad=True)
tensor([0.1831])


In [5]:
import torch.nn as nn
model=nn.Linear(11,1,True)

In [7]:
pred=model(x_input)
print(pred)

tensor([[ 4.9270],
        [ 7.6525],
        [ 6.4376],
        ...,
        [13.0202],
        [ 3.7192],
        [ 3.4115]], grad_fn=<AddmmBackward>)
